# Change these first
owner: darioxmastodon # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
runner: "[self-hosted]"

sites:
  - name: Mastodon
    url: https://dariox.club
    expectedStatusCodes:
      - 200
  - name: Media
    url: http://assets.dariox.club
    expectedStatusCodes:
      - 200
      - 404
      - 403

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dariox.club
  logoUrl: https://res.kate.pet/upload/88d01781-a04c-4f68-8cfd-85b46d9601c4/dariox-mastodon-logo-small.png
  name: DARiOX
  introTitle: "DARiOX Status Page"
  introMessage: DARiOX is a Mastodon instance for tech-centered LGBTQI+ folks and furries. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Mastodon
      href: https://dariox.club

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
